<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SalcosComfortKit.Server</RootNamespace>
    <AssemblyName>SalcosComfortKit.Server</AssemblyName>
    <Version>0.3.1</Version>
    <AssemblyVersion>0.3.1.0</AssemblyVersion>
    <FileVersion>0.3.1.0</FileVersion>
    <Description>Server-side package component for Salco's Comfort Kit.</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
  </ItemGroup>
</Project>
